Feature/main page updates
ucfcs/Fall2020-Group44 pull request #101
Opened 2021-03-12 02:39 UTC by ljoks

fixes minor things that were bugging me: 
- truncating long titles in the content tree
- max title length in the create title modal
- display the folder in the question preview

2021-03-12 03:18 UTC, weining-li requested changes
:cactus:

2021-03-12 03:18 UTC, weining-li commented on frontend/src/components/home-page/content-tree/content-tree.tsx
> +                                                  {truncate(question.title)}
add
```
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
```
to the `title` class
```
  .title,
  .type {
    overflow: hidden;
    font-size: 1.25rem;
  }
```
to have ellipsis replace text longer than 2 lines.

2021-03-12 03:18 UTC, weining-li commented on frontend/src/components/creator-module/creator-edit/creator-edit.tsx
> +            value={newQuestion.title}
add `maxLength` attribute to the input element to limit characters.
for example `maxlength={50}`

2021-03-12 04:12 UTC, weining-li approved these changes
:u5272:

2021-03-12 14:01 UTC, Goff-Davis approved these changes
Minor thing but looks good to me

2021-03-12 14:01 UTC, Goff-Davis commented on frontend/src/components/home-page/question-preview/question-preview.scss
> +    // border: 1px solid red;
No need to keep commented code

2021-03-13 17:55 UTC, Goff-Davis approved these changes
LGTM

2021-03-14 15:38 UTC, merged