Update LTI 1.3 integration
ucfcs/Fall2020-Group44 pull request #170
Opened 2021-03-29 22:23 UTC by vutoan1245

2021-03-29 22:27 UTC, kennygperez commented on backend/src/handlers/auth/lti.ts
> +	const url =
that's a long url lol

2021-04-04 21:25 UTC, kennygperez commented on backend/serverless.yml
> +          path: /api/v1/auth/login
Fix the paths to follow the following convention

`api/v1/auth/{PLATFORM}/{ACTION}`

2021-04-04 21:25 UTC, kennygperez requested changes
Change URL schema

2021-04-05 01:49 UTC, ljoks submitted a review, later dismissed

2021-04-05 15:23 UTC, kennygperez approved these changes
Niceeee

2021-04-05 15:24 UTC, kennygperez commented
@vutoan1245 merge when ready

2021-04-05 19:04 UTC, merged