Issue/185 calculate grades
ucfcs/Fall2020-Group44 pull request #198
Opened 2021-04-08 22:57 UTC by ljoks

currently uses mock users. that will have to change when we figure out how to get users from an LTI. 

calculates grades for 25 mock users, `userId`s 1-25

2021-04-09 13:42 UTC, kennygperez commented on backend/src/@types/models/Question.d.ts
> +	QuestionOptions: Array<QuestionOption>;
Change this to `QuestionOption[]`

2021-04-09 13:42 UTC, kennygperez commented on backend/src/@types/models/SessionGrade.d.ts
> +	QuestionGrades: Array<QuestionGrade>;
Same here

2021-04-09 13:42 UTC, kennygperez commented on backend/src/@types/models/SessionGrade.d.ts
> +	QuestionGrades: Array<QuestionGrade>;
And here

2021-04-09 13:42 UTC, kennygperez commented on backend/src/handlers/question.ts
> +	console.log(body);
Remove console log

2021-04-09 13:43 UTC, kennygperez commented on backend/src/handlers/sessionGrades.ts
> +// import fetch from 'node-fetch';
Remove commented code

2021-04-09 13:44 UTC, kennygperez requested changes
Just change a few things, super ez

2021-04-09 16:04 UTC, Goff-Davis reviewed
Looks good other than the changes kenny requested 👍

2021-04-10 21:58 UTC, Goff-Davis submitted a review, later dismissed

2021-04-10 23:53 UTC, merged